### ISSUE TITLE
Chat dialog loses entered-text if a new message appears

### ISSUE THREAD

**Issue by TheFifthHorseman** [MechWarriorOnline/issue-tracker#160] opened 2017-07-25 21:02 UTC
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
If the player types in a message and another player sends one, the contents of the text input field are cleared. This can render the chat nearly unusable for some players.

**Comment by tauSentry** [comment] 2017-07-27 21:28
Update:  
It looks like this issue is getting fixed in Patch X.X.XXX (July 27). Will confirm on release day.
http://www.mwomercs.com/news/2017/07/1864-hotfix-scheduled-for-27jul2017

**Comment by tauSentry** [comment] 2017-07-31 02:59
Confirmed fixed. Closing issue.

**Closed by tauSentry** 2017-07-31 02:59 UTC
Labels: Status: Fixed, Type: Bug
