### ISSUE TITLE
Skill Tree - Save and load preset templates

### ISSUE THREAD

**Issue by kjrhanson** [MechWarriorOnline/issue-tracker#123] opened 2017-05-29 15:28 UTC
I would like to be able to pre-allocate points and then save them, to load on different mechs and reduce the amount of clicking required.  

Example:

If I were going down the Sensors tree in a basic template, I'd get something like this (https://tarogato-mwo.github.io/mwo_skill_planner/?77d89837-4482-11e7-ae4c-33745f2903ba) and save it as "Sensors."  This is a basic set of skills that I would use on most mechs.

When skilling a new mech, I would go to "Load Template" and select "Sensors"

The Template would highlight the nodes that I have selected, how many skill points it uses, and which skills are selected.  You know, like a template. :)

If there aren't enough points, then the template would offer the option of "Fill in with as many free nodes as possible" or "Do not load template"

En masse, I could Load "Sensors" "Armor" and "Ops" and see how many points I have left for the Weapons tree.  3 templates for 60+ points would be very handy.

**Comment by tauSentry** [comment] 2017-05-29 16:54
Administrivia...
This appears to be a duplicate of Issue #86. @kjrhanson, can you confirm.

**Comment by kjrhanson** [comment] 2017-05-29 16:56
Didn't see it by name, but yes, duplicate.  Please close if need be.

**Comment by tauSentry** [comment] 2017-05-29 20:30
Your submission is more detailed (thank you for that, btw). I will copy your details to the other one. I will probably also change the title of the other one so that it can be found more easily.

**Closed by tauSentry** 2017-05-29 20:30 UTC
Labels: Status: Duplicate
