### ISSUE TITLE
Mechlab floating window doesn't disappear

### ISSUE THREAD

**Issue by TheEmperorOfMankind** [MechWarriorOnline/issue-tracker#168] opened 2017-08-19 18:54 UTC
There is a floating window which doesn't disappear and stays on top. I don't know how to reproduce this yet, but it happens from time to time.

[Proof1](https://i.imgur.com/5h1kIfl.jpg)
[Proof2](https://i.imgur.com/6xDiBoq.png)
[Proof3](https://i.imgur.com/2acqIaK.jpg)

**Comment by tauSentry** [comment] 2017-08-20 17:31
Administrivia...  
Hi @TheEmperorOfMankind, thanks for the bug report.  
This one looks like a duplicate of Issue #129.  
I'll go ahead and add your screenshots to that Issue and close this one.  
- Thank you for adding screenshots, btw. They're always helpful. :)

**Closed by tauSentry** 2017-08-20 17:31 UTC
